;░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
;░This file is part of libfastasm.										░
;░																		░
;░libfastasm is free software: you can redistribute it and/or modify	░
;░it under the terms of the GNU General Public License as published by	░
;░the Free Software Foundation, either version 3 of the License, or		░
;░(at your option) any later version.									░
;░																		░
;░libfastasm is distributed in the hope that it will be useful,			░
;░but WITHOUT ANY WARRANTY; without even the implied warranty of		░
;░MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the			░
;░GNU General Public License for more details.							░
;░																		░
;░You should have received a copy of the GNU General Public License		░
;░along with Foobar.  If not, see <https://www.gnu.org/licenses/>.		░
;░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
import	libfastasm,\
		fa_cabs,'fa_cabs',\
		fa_carg,'fa_carg',\
		fa_cimag,'fa_cimag',\
		fa_creal,'fa_creal',\
		fa_abs,'fa_abs',\
		fa_cos,'fa_cos',\
		fa_deg2rad,'fa_deg2rad',\
		fa_fabs,'fa_fabs',\
		fa_hypot,'fa_hypot',\
		fa_pow2,'fa_pow2',\
		fa_pow10,'fa_pow10',\
		fa_round,'fa_round',\
		fa_sin,'fa_sin',\
		fa_sqrt,'fa_sqrt',\
		fa_trunc,'fa_trunc',\
		fa_putchar,'fa_putchar',\
		fa_atoi,'fa_atoi',\
		fa_atoui,'fa_atoui',\
		fa_exit,'fa_exit',\
		fa_ftoa,'fa_ftoa',\
		fa_itoa,'fa_itoa',\
		fa_malloc,'fa_malloc',\
		fa_rand,'fa_rand',\
		fa_memset,'fa_memset',\
		fa_strcat,'fa_strcat',\
		fa_strcmp,'fa_strcmp',\
		fa_strcpy,'fa_strcpy',\
		fa_strlen,'fa_strlen',\
		fa_time,'fa_time'